name: CI

on: [push]

jobs:
  build:
    name: hello wolrd action
    runs-on: ubuntu-latest

    steps:
    - name: checkout source code
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo kiwinam
        echo first action
